<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPUAKYIW0675" name="Smoke test for calculation" tests="67" failures="16" timestamp="1 Nov 2016 17:39:09 GMT" time="7.27" errors="0">
  <testcase name="testCos" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [0.9480811024049992] but found [0.3180286516377352]">
      <![CDATA[java.lang.AssertionError: expected [0.9480811024049992] but found [0.3180286516377352]
	at businessObject.CalculatorTest.testCos(CalculatorTest.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testSqrt" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testDivLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSin" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testCtg" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [2.981118517223813] but found [-1.0]">
      <![CDATA[java.lang.AssertionError: expected [2.981118517223813] but found [-1.0]
	at businessObject.CalculatorTest.testCtg(CalculatorTest.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testCos" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [0.0]
	at businessObject.CalculatorTest.testCos(CalculatorTest.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testCtg" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [-0.1405626691891154] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [-0.1405626691891154] but found [1.0]
	at businessObject.CalculatorTest.testCtg(CalculatorTest.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testSqrt" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSqrt" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testIsNegative" time="0.031" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultDouble" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [2740734.0] but found [2858587.0]">
      <![CDATA[java.lang.AssertionError: expected [2740734.0] but found [2858587.0]
	at businessObject.CalculatorTest.testMultDouble(CalculatorTest.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testMultDouble -->
  <testcase name="testMultDouble" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [25.0] but found [27.0]">
      <![CDATA[java.lang.AssertionError: expected [25.0] but found [27.0]
	at businessObject.CalculatorTest.testMultDouble(CalculatorTest.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testMultDouble -->
  <testcase name="testMultDouble" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [-150.0] but found [-159.0]">
      <![CDATA[java.lang.AssertionError: expected [-150.0] but found [-159.0]
	at businessObject.CalculatorTest.testMultDouble(CalculatorTest.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testMultDouble -->
  <testcase name="testMultDouble" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [-160.0] but found [-167.0]">
      <![CDATA[java.lang.AssertionError: expected [-160.0] but found [-167.0]
	at businessObject.CalculatorTest.testMultDouble(CalculatorTest.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testMultDouble -->
  <testcase name="testIsPositive" time="0.052" classname="businessObject.CalculatorTest"/>
  <testcase name="testIsPositive" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at businessObject.CalculatorTest.testIsPositive(CalculatorTest.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testIsPositive -->
  <testcase name="testSin" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSin" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSin" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubDouble" time="0.053" classname="businessObject.CalculatorTest"/>
  <testcase name="testPow" time="0.053" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumDouble" time="0.016" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testPow" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testDivLong" time="0.016" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubLong" time="0.021" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubLong" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [9223372036854775807] but found [9223372036854775709]">
      <![CDATA[java.lang.AssertionError: expected [9223372036854775807] but found [9223372036854775709]
	at businessObject.CalculatorTest.testSubLong(CalculatorTest.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testSubLong -->
  <testcase name="testSubDouble" time="0.016" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubDouble" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [-5.6562979E7] but found [-5.6562067E7]">
      <![CDATA[java.lang.AssertionError: expected [-5.6562979E7] but found [-5.6562067E7]
	at businessObject.CalculatorTest.testSubDouble(CalculatorTest.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testSubDouble -->
  <testcase name="testSubLong" time="0.015" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [56562979] but found [-56562067]">
      <![CDATA[java.lang.AssertionError: expected [56562979] but found [-56562067]
	at businessObject.CalculatorTest.testSubLong(CalculatorTest.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testSubLong -->
  <testcase name="testSubLong" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [824682468246]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [824682468246]
	at businessObject.CalculatorTest.testSubLong(CalculatorTest.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testSubLong -->
  <testcase name="testSubLong" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [555555555555550] but found [-555555555555560]">
      <![CDATA[java.lang.AssertionError: expected [555555555555550] but found [-555555555555560]
	at businessObject.CalculatorTest.testSubLong(CalculatorTest.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testSubLong -->
  <testcase name="testDivLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testDivLong" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testPow" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testMultLong" time="0.047" classname="businessObject.CalculatorTest"/>
  <testcase name="testSubDouble" time="0.031" classname="businessObject.CalculatorTest"/>
  <testcase name="testCos" time="0.031" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [-0.13919430405964572] but found [0.9902650886087779]">
      <![CDATA[java.lang.AssertionError: expected [-0.13919430405964572] but found [0.9902650886087779]
	at businessObject.CalculatorTest.testCos(CalculatorTest.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testCos" time="0.0" classname="businessObject.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [0.5403023058681398] but found [0.8414709848078965]">
      <![CDATA[java.lang.AssertionError: expected [0.5403023058681398] but found [0.8414709848078965]
	at businessObject.CalculatorTest.testCos(CalculatorTest.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testSubDouble" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testPow" time="0.016" classname="businessObject.CalculatorTest"/>
  <testcase name="testPow" time="0.0" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumLong" time="1.009" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumLong" time="1.006" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumLong" time="1.001" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumLong" time="1.015" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumLong" time="1.001" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumLong" time="1.001" classname="businessObject.CalculatorTest"/>
  <testcase name="testSumLong" time="1.006" classname="businessObject.CalculatorTest"/>
</testsuite> <!-- Smoke test for calculation -->
